openapi: 3.0.0
servers: []
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: hudaszekmichal@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: upload
    description: Secured Admin-only calls
paths:
  /v1/upload:
    post:
      security:
        - bearerAuth: []
      tags:
        - upload
      summary: adds an inventory item
      operationId: addInventory
      description: Adds an item to the system
      responses:
        '200':
          description: 'Items uploaded'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 2058959
                    timestamp:
                      type: string
                      example: 1516354800
                    source:
                      type: string
                      example: instagram
                    folder:
                      type: string
                      example: null
                    height:
                      type: integer
                      example: 1080  
                    width:
                      type: integer
                      example: 1080   
                    mime:
                      type: string
                      example: image/jpeg 
                    display:
                      type: array
                      items:
                        type: object
                        properties:
                          thumbnail:
                            type: object
                            properties:
                              height:
                                type: integer
                                example: 200  
                              width:
                                type: integer
                                example: 200
                              src:
                                type: string
                                example: https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIGW4VGE1cuYIyIE/image.jpg
                          preview:
                            type: object
                            properties:
                              height:
                                type: integer
                                example: 800  
                              width:
                                type: integer
                                example: 800
                              src:
                                type: string
                                example: https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIsI%252BRE60RFRtAsn/image.jpg
                          square:
                            type: object
                            properties:
                              height:
                                type: integer
                                example: 200  
                              width:
                                type: integer
                                example: 200
                              src:
                                type: string
                                example: https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIsI%252BRE60RFRtAsn/image.jpg
                          original:
                            type: object
                            properties:
                              height:
                                type: integer
                                example: 1080  
                              width:
                                type: integer
                                example: 1080
                              src:
                                type: string
                                example: https://dev-printu-net.s3.eu-central-1.amazonaws.com/photobook/12/7/0/2058959.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAILKHTK5ZOAVQB23Q%2F20180209%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20180209T092316Z&X-Amz-SignedHeaders=host&X-Amz-Expires=518400&X-Amz-Signature=cc95d836e2235992e1948add1bc8f5cdb35d39dc974f8cfa23efd9895db32d38      
                    metadata:
                      type: object
                      properties:
                        gps:
                          type: string
                          example: 52/1, 15/1, 272/100 N 21/1, 1/1, 5851/100 E  
                        datetime:
                          type: integer
                          example: 1516354800
                        name:
                          type: string
                          example: IMG_9171.JPG
        '4XX':
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    errorCode:
                      type: integer
                      example: 400
                    userMessage:
                      type: string
                      example: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.
                    devMessage:
                      type: string
                      example: Check the client_id parameter.
                    more:
                      type: string
                      example: ""
                    applicationCode:
                      type: string
                      example: X1234
        '5XX':
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    errorCode:
                      type: integer
                      example: 400
                    userMessage:
                      type: string
                      example: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.
                    devMessage:
                      type: string
                      example: Check the client_id parameter.
                    more:
                      type: string
                      example: ""
                    applicationCode:
                      type: string
                      example: X1234              
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryItem'
        description: Inventory item to add
components:
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    InventoryItem:
      type: array
      items:
        type: object
        required:
          - part
          - etag
        properties:
          part:
            type: integer
          etag:
            type: string
            format: uuid
      example:
        - part: 1
          etag: a54357aff0632cce46d942af68356b38
        - part: 2
          etag: 0c78aef83f66abc1fa1e8477f296d394
        - part: 3
          etag: acbd18db4cc2f85cedef654fccc4a4d8